author: Brayan Sanjuan
name: Auto version Synchronization
description: "A GitHub Action to automatically sync project versions based on labels in pull requests. This action increments the software version in the package.json file and creates a new GitHub tag based on the configured PR labels, allowing for more efficient and automated version control."

inputs:
  current_version:
    default: 0.1.0
    required: false
    description: "The current version"

  level:
    default: minor
    required: false
    description: A semver update level ({major, minor, patch}).

outputs:
  new_version:
    description: The bumped semver version.
  new_version_without_v:
    description: The bumped semver version without "v".

runs:
  using: node20
  main: lib/index.js

branding:
  icon: check
  color: white
