author: Brayan Sanjuan
name: Auto version Synchronization
description: GitHub Action to auto-sync versions via PR labels, updating package.json and tagging for streamlined version control.

inputs:
  current_version:
    default: 0.1.0
    required: false
    description: "The current version"

  level:
    default: minor
    required: false
    description: A semver update level ({major, minor, patch}).

  git_username:
    required: false
    description: name of git

  git_email:
    required: false
    description: email of git

outputs:
  new_version:
    description: The bumped semver version.
  new_version_without_v:
    description: The bumped semver version without "v".

runs:
  using: node20
  main: lib/index.js

branding:
  icon: check
  color: white
