name: Auto version Synchronization
description: ""
author: Brayan Sanjuan

inputs:
  current_version:
    default: 0.1.0
    required: false
    description: "The current version"

  level:
    default: minor
    required: false
    description: A semver update level ({major, minor, patch}).

outputs:
  new_version:
    description: The bumped semver version.
  new_version_without_v:
    description: The bumped semver version without "v".

runs:
  using: node20
  main: lib/index.js

branding:
  icon: check
  color: white
